name: Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "5 1 * * *"

jobs:
  unit-test:
    name: Unit tests
    strategy:
      fail-fast: false
      matrix:
        go: [ '1.23', '1.24' ]
        os: [ 'windows-latest', 'ubuntu-latest', 'macOS-latest' ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Run Unit tests (Go ${{ matrix.go }})
        run: make test

  fmt:
    name: go fmt
    strategy:
      fail-fast: false
      matrix:
        go-version: [ '1.23', '1.24' ]
        os: [ 'windows-latest', 'ubuntu-latest', 'macOS-latest' ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v5
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run go fmt (Go ${{ matrix.go }})
        if: runner.os != 'Windows'
        run: diff -u <(echo -n) <(gofmt -d -s .)

  vet:
    name: go vet
    strategy:
      fail-fast: false
      matrix:
        go-version: [ '1.23', '1.24' ]
        os: [ 'windows-latest', 'ubuntu-latest', 'macOS-latest' ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v5
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run go vet
        run: make vet

  staticcheck:
    name: staticcheck
    strategy:
      fail-fast: false
      matrix:
        go-version: [ '1.23', '1.24' ]
        os: [ 'windows-latest', 'ubuntu-latest', 'macOS-latest' ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v5
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run staticcheck (Go ${{ matrix.go }})
        uses: dominikh/staticcheck-action@v1.4.0
        with:
          version: "2025.1.1"
          install-go: false
          cache-key: ${{ matrix.go-version }}-${{ matrix.os }}